//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProceso.ServicioFElectCR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFElectCR.wesDocumentosFiscalesSoap")]
    public interface wesDocumentosFiscalesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroDocumentoEmision", ReplyAction="*")]
        TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponse RegistroDocumentoEmision(TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroDocumentoEmision", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponse> RegistroDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecepcionRegistroDocumentoEmision", ReplyAction="*")]
        TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponse RecepcionRegistroDocumentoEmision(TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecepcionRegistroDocumentoEmision", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponse> RecepcionRegistroDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaDocumentoEmision", ReplyAction="*")]
        TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponse ConsultaDocumentoEmision(TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaDocumentoEmision", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponse> ConsultaDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaRespuestaHaciendaDocumentoEmision", ReplyAction="*")]
        TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponse ConsultaRespuestaHaciendaDocumentoEmision(TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaRespuestaHaciendaDocumentoEmision", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponse> ConsultaRespuestaHaciendaDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroEmisor", ReplyAction="*")]
        TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponse RegistroEmisor(TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroEmisor", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponse> RegistroEmisorAsync(TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroDocumentoEmisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroDocumentoEmision", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequestBody Body;
        
        public RegistroDocumentoEmisionRequest() {
        }
        
        public RegistroDocumentoEmisionRequest(TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroDocumentoEmisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string acInformacionCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acIdentificacionDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acTextoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string acRespuestaFiscal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string acMensaje;
        
        public RegistroDocumentoEmisionRequestBody() {
        }
        
        public RegistroDocumentoEmisionRequestBody(string acInformacionCliente, string acIdentificacionDocumento, string acTextoDocumento, string acRespuestaFiscal, string acMensaje) {
            this.acInformacionCliente = acInformacionCliente;
            this.acIdentificacionDocumento = acIdentificacionDocumento;
            this.acTextoDocumento = acTextoDocumento;
            this.acRespuestaFiscal = acRespuestaFiscal;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroDocumentoEmisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroDocumentoEmisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponseBody Body;
        
        public RegistroDocumentoEmisionResponse() {
        }
        
        public RegistroDocumentoEmisionResponse(TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroDocumentoEmisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistroDocumentoEmisionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acRespuestaFiscal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acMensaje;
        
        public RegistroDocumentoEmisionResponseBody() {
        }
        
        public RegistroDocumentoEmisionResponseBody(bool RegistroDocumentoEmisionResult, string acRespuestaFiscal, string acMensaje) {
            this.RegistroDocumentoEmisionResult = RegistroDocumentoEmisionResult;
            this.acRespuestaFiscal = acRespuestaFiscal;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionRegistroDocumentoEmisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionRegistroDocumentoEmision", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequestBody Body;
        
        public RecepcionRegistroDocumentoEmisionRequest() {
        }
        
        public RecepcionRegistroDocumentoEmisionRequest(TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecepcionRegistroDocumentoEmisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string acInformacionCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acIdentificacionDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acTextoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string acMensaje;
        
        public RecepcionRegistroDocumentoEmisionRequestBody() {
        }
        
        public RecepcionRegistroDocumentoEmisionRequestBody(string acInformacionCliente, string acIdentificacionDocumento, string acTextoDocumento, string acMensaje) {
            this.acInformacionCliente = acInformacionCliente;
            this.acIdentificacionDocumento = acIdentificacionDocumento;
            this.acTextoDocumento = acTextoDocumento;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionRegistroDocumentoEmisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionRegistroDocumentoEmisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponseBody Body;
        
        public RecepcionRegistroDocumentoEmisionResponse() {
        }
        
        public RecepcionRegistroDocumentoEmisionResponse(TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecepcionRegistroDocumentoEmisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RecepcionRegistroDocumentoEmisionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acMensaje;
        
        public RecepcionRegistroDocumentoEmisionResponseBody() {
        }
        
        public RecepcionRegistroDocumentoEmisionResponseBody(bool RecepcionRegistroDocumentoEmisionResult, string acMensaje) {
            this.RecepcionRegistroDocumentoEmisionResult = RecepcionRegistroDocumentoEmisionResult;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDocumentoEmisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaDocumentoEmision", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequestBody Body;
        
        public ConsultaDocumentoEmisionRequest() {
        }
        
        public ConsultaDocumentoEmisionRequest(TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaDocumentoEmisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string acInformacionCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acIdentificacionDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acRespuestaFiscal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string acMensaje;
        
        public ConsultaDocumentoEmisionRequestBody() {
        }
        
        public ConsultaDocumentoEmisionRequestBody(string acInformacionCliente, string acIdentificacionDocumento, string acRespuestaFiscal, string acMensaje) {
            this.acInformacionCliente = acInformacionCliente;
            this.acIdentificacionDocumento = acIdentificacionDocumento;
            this.acRespuestaFiscal = acRespuestaFiscal;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDocumentoEmisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaDocumentoEmisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponseBody Body;
        
        public ConsultaDocumentoEmisionResponse() {
        }
        
        public ConsultaDocumentoEmisionResponse(TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaDocumentoEmisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ConsultaDocumentoEmisionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acRespuestaFiscal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acMensaje;
        
        public ConsultaDocumentoEmisionResponseBody() {
        }
        
        public ConsultaDocumentoEmisionResponseBody(bool ConsultaDocumentoEmisionResult, string acRespuestaFiscal, string acMensaje) {
            this.ConsultaDocumentoEmisionResult = ConsultaDocumentoEmisionResult;
            this.acRespuestaFiscal = acRespuestaFiscal;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaRespuestaHaciendaDocumentoEmisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaRespuestaHaciendaDocumentoEmision", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequestBody Body;
        
        public ConsultaRespuestaHaciendaDocumentoEmisionRequest() {
        }
        
        public ConsultaRespuestaHaciendaDocumentoEmisionRequest(TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaRespuestaHaciendaDocumentoEmisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string acInformacionCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acClaveDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acRespuestaHacienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string acMensaje;
        
        public ConsultaRespuestaHaciendaDocumentoEmisionRequestBody() {
        }
        
        public ConsultaRespuestaHaciendaDocumentoEmisionRequestBody(string acInformacionCliente, string acClaveDocumento, string acRespuestaHacienda, string acMensaje) {
            this.acInformacionCliente = acInformacionCliente;
            this.acClaveDocumento = acClaveDocumento;
            this.acRespuestaHacienda = acRespuestaHacienda;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaRespuestaHaciendaDocumentoEmisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaRespuestaHaciendaDocumentoEmisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponseBody Body;
        
        public ConsultaRespuestaHaciendaDocumentoEmisionResponse() {
        }
        
        public ConsultaRespuestaHaciendaDocumentoEmisionResponse(TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaRespuestaHaciendaDocumentoEmisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ConsultaRespuestaHaciendaDocumentoEmisionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acRespuestaHacienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acMensaje;
        
        public ConsultaRespuestaHaciendaDocumentoEmisionResponseBody() {
        }
        
        public ConsultaRespuestaHaciendaDocumentoEmisionResponseBody(bool ConsultaRespuestaHaciendaDocumentoEmisionResult, string acRespuestaHacienda, string acMensaje) {
            this.ConsultaRespuestaHaciendaDocumentoEmisionResult = ConsultaRespuestaHaciendaDocumentoEmisionResult;
            this.acRespuestaHacienda = acRespuestaHacienda;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroEmisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroEmisor", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequestBody Body;
        
        public RegistroEmisorRequest() {
        }
        
        public RegistroEmisorRequest(TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroEmisorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string acInformacionCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acIdentificacionEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acTextoEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string acMensaje;
        
        public RegistroEmisorRequestBody() {
        }
        
        public RegistroEmisorRequestBody(string acInformacionCliente, string acIdentificacionEmisor, string acTextoEmisor, string acMensaje) {
            this.acInformacionCliente = acInformacionCliente;
            this.acIdentificacionEmisor = acIdentificacionEmisor;
            this.acTextoEmisor = acTextoEmisor;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroEmisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroEmisorResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponseBody Body;
        
        public RegistroEmisorResponse() {
        }
        
        public RegistroEmisorResponse(TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroEmisorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistroEmisorResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string acMensaje;
        
        public RegistroEmisorResponseBody() {
        }
        
        public RegistroEmisorResponseBody(bool RegistroEmisorResult, string acMensaje) {
            this.RegistroEmisorResult = RegistroEmisorResult;
            this.acMensaje = acMensaje;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wesDocumentosFiscalesSoapChannel : TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wesDocumentosFiscalesSoapClient : System.ServiceModel.ClientBase<TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap>, TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap {
        
        public wesDocumentosFiscalesSoapClient() {
        }
        
        public wesDocumentosFiscalesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wesDocumentosFiscalesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wesDocumentosFiscalesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wesDocumentosFiscalesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponse TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.RegistroDocumentoEmision(TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest request) {
            return base.Channel.RegistroDocumentoEmision(request);
        }
        
        public bool RegistroDocumentoEmision(string acInformacionCliente, string acIdentificacionDocumento, string acTextoDocumento, ref string acRespuestaFiscal, ref string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionDocumento = acIdentificacionDocumento;
            inValue.Body.acTextoDocumento = acTextoDocumento;
            inValue.Body.acRespuestaFiscal = acRespuestaFiscal;
            inValue.Body.acMensaje = acMensaje;
            TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponse retVal = ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).RegistroDocumentoEmision(inValue);
            acRespuestaFiscal = retVal.Body.acRespuestaFiscal;
            acMensaje = retVal.Body.acMensaje;
            return retVal.Body.RegistroDocumentoEmisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponse> TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.RegistroDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest request) {
            return base.Channel.RegistroDocumentoEmisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionResponse> RegistroDocumentoEmisionAsync(string acInformacionCliente, string acIdentificacionDocumento, string acTextoDocumento, string acRespuestaFiscal, string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.RegistroDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionDocumento = acIdentificacionDocumento;
            inValue.Body.acTextoDocumento = acTextoDocumento;
            inValue.Body.acRespuestaFiscal = acRespuestaFiscal;
            inValue.Body.acMensaje = acMensaje;
            return ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).RegistroDocumentoEmisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponse TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.RecepcionRegistroDocumentoEmision(TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest request) {
            return base.Channel.RecepcionRegistroDocumentoEmision(request);
        }
        
        public bool RecepcionRegistroDocumentoEmision(string acInformacionCliente, string acIdentificacionDocumento, string acTextoDocumento, ref string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionDocumento = acIdentificacionDocumento;
            inValue.Body.acTextoDocumento = acTextoDocumento;
            inValue.Body.acMensaje = acMensaje;
            TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponse retVal = ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).RecepcionRegistroDocumentoEmision(inValue);
            acMensaje = retVal.Body.acMensaje;
            return retVal.Body.RecepcionRegistroDocumentoEmisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponse> TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.RecepcionRegistroDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest request) {
            return base.Channel.RecepcionRegistroDocumentoEmisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionResponse> RecepcionRegistroDocumentoEmisionAsync(string acInformacionCliente, string acIdentificacionDocumento, string acTextoDocumento, string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.RecepcionRegistroDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionDocumento = acIdentificacionDocumento;
            inValue.Body.acTextoDocumento = acTextoDocumento;
            inValue.Body.acMensaje = acMensaje;
            return ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).RecepcionRegistroDocumentoEmisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponse TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.ConsultaDocumentoEmision(TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest request) {
            return base.Channel.ConsultaDocumentoEmision(request);
        }
        
        public bool ConsultaDocumentoEmision(string acInformacionCliente, string acIdentificacionDocumento, ref string acRespuestaFiscal, ref string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionDocumento = acIdentificacionDocumento;
            inValue.Body.acRespuestaFiscal = acRespuestaFiscal;
            inValue.Body.acMensaje = acMensaje;
            TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponse retVal = ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).ConsultaDocumentoEmision(inValue);
            acRespuestaFiscal = retVal.Body.acRespuestaFiscal;
            acMensaje = retVal.Body.acMensaje;
            return retVal.Body.ConsultaDocumentoEmisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponse> TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.ConsultaDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest request) {
            return base.Channel.ConsultaDocumentoEmisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionResponse> ConsultaDocumentoEmisionAsync(string acInformacionCliente, string acIdentificacionDocumento, string acRespuestaFiscal, string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.ConsultaDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionDocumento = acIdentificacionDocumento;
            inValue.Body.acRespuestaFiscal = acRespuestaFiscal;
            inValue.Body.acMensaje = acMensaje;
            return ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).ConsultaDocumentoEmisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponse TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.ConsultaRespuestaHaciendaDocumentoEmision(TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest request) {
            return base.Channel.ConsultaRespuestaHaciendaDocumentoEmision(request);
        }
        
        public bool ConsultaRespuestaHaciendaDocumentoEmision(string acInformacionCliente, string acClaveDocumento, ref string acRespuestaHacienda, ref string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acClaveDocumento = acClaveDocumento;
            inValue.Body.acRespuestaHacienda = acRespuestaHacienda;
            inValue.Body.acMensaje = acMensaje;
            TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponse retVal = ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).ConsultaRespuestaHaciendaDocumentoEmision(inValue);
            acRespuestaHacienda = retVal.Body.acRespuestaHacienda;
            acMensaje = retVal.Body.acMensaje;
            return retVal.Body.ConsultaRespuestaHaciendaDocumentoEmisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponse> TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.ConsultaRespuestaHaciendaDocumentoEmisionAsync(TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest request) {
            return base.Channel.ConsultaRespuestaHaciendaDocumentoEmisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionResponse> ConsultaRespuestaHaciendaDocumentoEmisionAsync(string acInformacionCliente, string acClaveDocumento, string acRespuestaHacienda, string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest inValue = new TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.ConsultaRespuestaHaciendaDocumentoEmisionRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acClaveDocumento = acClaveDocumento;
            inValue.Body.acRespuestaHacienda = acRespuestaHacienda;
            inValue.Body.acMensaje = acMensaje;
            return ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).ConsultaRespuestaHaciendaDocumentoEmisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponse TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.RegistroEmisor(TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest request) {
            return base.Channel.RegistroEmisor(request);
        }
        
        public bool RegistroEmisor(string acInformacionCliente, string acIdentificacionEmisor, string acTextoEmisor, ref string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest inValue = new TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionEmisor = acIdentificacionEmisor;
            inValue.Body.acTextoEmisor = acTextoEmisor;
            inValue.Body.acMensaje = acMensaje;
            TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponse retVal = ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).RegistroEmisor(inValue);
            acMensaje = retVal.Body.acMensaje;
            return retVal.Body.RegistroEmisorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponse> TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap.RegistroEmisorAsync(TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest request) {
            return base.Channel.RegistroEmisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioFElectCR.RegistroEmisorResponse> RegistroEmisorAsync(string acInformacionCliente, string acIdentificacionEmisor, string acTextoEmisor, string acMensaje) {
            TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest inValue = new TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequest();
            inValue.Body = new TiempoEnProceso.ServicioFElectCR.RegistroEmisorRequestBody();
            inValue.Body.acInformacionCliente = acInformacionCliente;
            inValue.Body.acIdentificacionEmisor = acIdentificacionEmisor;
            inValue.Body.acTextoEmisor = acTextoEmisor;
            inValue.Body.acMensaje = acMensaje;
            return ((TiempoEnProceso.ServicioFElectCR.wesDocumentosFiscalesSoap)(this)).RegistroEmisorAsync(inValue);
        }
    }
}
