//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProceso.ServicioTipoCambio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class InfoVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiempoEnProceso.ServicioTipoCambio.Variable[] VariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiempoEnProceso.ServicioTipoCambio.Var[] CambioDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiempoEnProceso.ServicioTipoCambio.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TiempoEnProceso.ServicioTipoCambio.Variable[] Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TiempoEnProceso.ServicioTipoCambio.Var[] CambioDia {
            get {
                return this.CambioDiaField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDiaField, value) != true)) {
                    this.CambioDiaField = value;
                    this.RaisePropertyChanged("CambioDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TiempoEnProceso.ServicioTipoCambio.VarDolar[] CambioDolar {
            get {
                return this.CambioDolarField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDolarField, value) != true)) {
                    this.CambioDolarField = value;
                    this.RaisePropertyChanged("CambioDolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Variable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Var : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta {
            get {
                return this.ventaField;
            }
            set {
                if ((this.ventaField.Equals(value) != true)) {
                    this.ventaField = value;
                    this.RaisePropertyChanged("venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra {
            get {
                return this.compraField;
            }
            set {
                if ((this.compraField.Equals(value) != true)) {
                    this.compraField = value;
                    this.RaisePropertyChanged("compra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class VarDolar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float referenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia {
            get {
                return this.referenciaField;
            }
            set {
                if ((this.referenciaField.Equals(value) != true)) {
                    this.referenciaField = value;
                    this.RaisePropertyChanged("referencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class DataVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiempoEnProceso.ServicioTipoCambio.Var[] VarsField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TiempoEnProceso.ServicioTipoCambio.Var[] Vars {
            get {
                return this.VarsField;
            }
            set {
                if ((object.ReferenceEquals(this.VarsField, value) != true)) {
                    this.VarsField = value;
                    this.RaisePropertyChanged("Vars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="ServicioTipoCambio.TipoCambioSoap")]
    public interface TipoCambioSoap {
        
        // CODEGEN: Generating message contract since element name VariablesDisponiblesResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponse VariablesDisponibles(TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync(TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest request);
        
        // CODEGEN: Generating message contract since element name VariablesResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.VariablesResponse Variables(TiempoEnProceso.ServicioTipoCambio.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.VariablesResponse> VariablesAsync(TiempoEnProceso.ServicioTipoCambio.VariablesRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponse TipoCambioFechaInicial(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponse TipoCambioRango(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponse TipoCambioFechaInicialMoneda(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponse TipoCambioRangoMoneda(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest request);
        
        // CODEGEN: Generating message contract since element name TipoCambioDiaResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponse TipoCambioDia(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest request);
        
        // CODEGEN: Generating message contract since element name TipoCambioDiaStringResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponse TipoCambioDiaString(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest() {
        }
        
        public VariablesDisponiblesRequest(TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody {
        
        public VariablesDisponiblesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse() {
        }
        
        public VariablesDisponiblesResponse(TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody() {
        }
        
        public VariablesDisponiblesResponseBody(TiempoEnProceso.ServicioTipoCambio.InfoVariable VariablesDisponiblesResult) {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.VariablesRequestBody Body;
        
        public VariablesRequest() {
        }
        
        public VariablesRequest(TiempoEnProceso.ServicioTipoCambio.VariablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody() {
        }
        
        public VariablesRequestBody(int variable) {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.VariablesResponseBody Body;
        
        public VariablesResponse() {
        }
        
        public VariablesResponse(TiempoEnProceso.ServicioTipoCambio.VariablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.InfoVariable VariablesResult;
        
        public VariablesResponseBody() {
        }
        
        public VariablesResponseBody(TiempoEnProceso.ServicioTipoCambio.InfoVariable VariablesResult) {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest() {
        }
        
        public TipoCambioFechaInicialRequest(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody() {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit) {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse() {
        }
        
        public TipoCambioFechaInicialResponse(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody() {
        }
        
        public TipoCambioFechaInicialResponseBody(TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioFechaInicialResult) {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest() {
        }
        
        public TipoCambioRangoRequest(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody() {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse() {
        }
        
        public TipoCambioRangoResponse(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody() {
        }
        
        public TipoCambioRangoResponseBody(TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioRangoResult) {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest() {
        }
        
        public TipoCambioFechaInicialMonedaRequest(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody() {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda) {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse() {
        }
        
        public TipoCambioFechaInicialMonedaResponse(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody() {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioFechaInicialMonedaResult) {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest() {
        }
        
        public TipoCambioRangoMonedaRequest(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody() {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse() {
        }
        
        public TipoCambioRangoMonedaResponse(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody() {
        }
        
        public TipoCambioRangoMonedaResponseBody(TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioRangoMonedaResult) {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest() {
        }
        
        public TipoCambioDiaRequest(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody {
        
        public TipoCambioDiaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse() {
        }
        
        public TipoCambioDiaResponse(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody() {
        }
        
        public TipoCambioDiaResponseBody(TiempoEnProceso.ServicioTipoCambio.InfoVariable TipoCambioDiaResult) {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest() {
        }
        
        public TipoCambioDiaStringRequest(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody {
        
        public TipoCambioDiaStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse() {
        }
        
        public TipoCambioDiaStringResponse(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody() {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult) {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoCambioSoapChannel : TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap>, TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap {
        
        public TipoCambioSoapClient() {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.VariablesDisponibles(TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponibles(request);
        }
        
        public TiempoEnProceso.ServicioTipoCambio.InfoVariable VariablesDisponibles() {
            TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest inValue = new TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequestBody();
            TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).VariablesDisponibles(inValue);
            return retVal.Body.VariablesDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.VariablesDisponiblesAsync(TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync() {
            TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest inValue = new TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.VariablesDisponiblesRequestBody();
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.VariablesResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.Variables(TiempoEnProceso.ServicioTipoCambio.VariablesRequest request) {
            return base.Channel.Variables(request);
        }
        
        public TiempoEnProceso.ServicioTipoCambio.InfoVariable Variables(int variable) {
            TiempoEnProceso.ServicioTipoCambio.VariablesRequest inValue = new TiempoEnProceso.ServicioTipoCambio.VariablesRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.VariablesRequestBody();
            inValue.Body.variable = variable;
            TiempoEnProceso.ServicioTipoCambio.VariablesResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).Variables(inValue);
            return retVal.Body.VariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.VariablesResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.VariablesAsync(TiempoEnProceso.ServicioTipoCambio.VariablesRequest request) {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.VariablesResponse> VariablesAsync(int variable) {
            TiempoEnProceso.ServicioTipoCambio.VariablesRequest inValue = new TiempoEnProceso.ServicioTipoCambio.VariablesRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioFechaInicial(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicial(request);
        }
        
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioFechaInicial(string fechainit) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicial(inValue);
            return retVal.Body.TipoCambioFechaInicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioFechaInicialAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioRango(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRango(request);
        }
        
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioRango(string fechainit, string fechafin) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioRango(inValue);
            return retVal.Body.TipoCambioRangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioRangoAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioFechaInicialMoneda(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMoneda(request);
        }
        
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioFechaInicialMoneda(string fechainit, int moneda) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialMoneda(inValue);
            return retVal.Body.TipoCambioFechaInicialMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioRangoMoneda(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMoneda(request);
        }
        
        public TiempoEnProceso.ServicioTipoCambio.DataVariable TipoCambioRangoMoneda(string fechainit, string fechafin, int moneda) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoMoneda(inValue);
            return retVal.Body.TipoCambioRangoMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioRangoMonedaAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda) {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioDia(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDia(request);
        }
        
        public TiempoEnProceso.ServicioTipoCambio.InfoVariable TipoCambioDia() {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequestBody();
            TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioDia(inValue);
            return retVal.Body.TipoCambioDiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioDiaAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync() {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaRequestBody();
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponse TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioDiaString(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaString(request);
        }
        
        public string TipoCambioDiaString() {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequestBody();
            TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponse retVal = ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaString(inValue);
            return retVal.Body.TipoCambioDiaStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponse> TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap.TipoCambioDiaStringAsync(TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync() {
            TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest inValue = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequest();
            inValue.Body = new TiempoEnProceso.ServicioTipoCambio.TipoCambioDiaStringRequestBody();
            return ((TiempoEnProceso.ServicioTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
    }
}
