//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAES_Solicitados
    {
        public string EMPRESA { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string SERIE { get; set; }
        public string NUMERO { get; set; }
        public string Ambiente { get; set; }
        public bool Es_Anulado { get; set; }
        public decimal Descuento { get; set; }
        public decimal Sub_Total { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public string firma_electronica { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public decimal tipo_cambio { get; set; }
        public string concepto { get; set; }
    }
}
