//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teams
    {
        public string id_team { get; set; }
        public string id_pais { get; set; }
        public string id_oficina { get; set; }
        public string Lider { get; set; }
        public Nullable<decimal> presupuesto_horas { get; set; }
        public string nombre { get; set; }
    }
}
