//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detalle_cargable
    {
        public decimal id_reporte { get; set; }
        public decimal linea { get; set; }
        public Nullable<decimal> horas { get; set; }
        public Nullable<decimal> honorarios { get; set; }
        public Nullable<decimal> gastos { get; set; }
        public Nullable<decimal> cuota_facturacion { get; set; }
        public string id_job { get; set; }
        public string descripcion_cargo { get; set; }
        public Nullable<decimal> autorizado { get; set; }
        public string id_oficina0 { get; set; }
        public string id_empleado { get; set; }
        public string id_cliente { get; set; }
        public Nullable<decimal> horasxautencargado { get; set; }
        public Nullable<decimal> horasxautorizar { get; set; }
        public string autorizotl { get; set; }
        public string autorizoenc { get; set; }
        public Nullable<decimal> horasrechazadas { get; set; }
        public Nullable<decimal> horasrechazadas_enc { get; set; }
        public Nullable<decimal> horascaptadasweb { get; set; }
        public decimal honorarioscaptadosweb { get; set; }
        public decimal gastoscaptadosweb { get; set; }
        public string Id_departamento { get; set; }
        public string Id_team { get; set; }
        public Nullable<System.DateTime> fecha_hora_captura { get; set; }
        public Nullable<decimal> id_tbl_entes_clientes { get; set; }
    }
}
