//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_gts_automaticos
    {
        public decimal Id_transaccion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Tipo_distribucion { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Periodo_tep_proceso { get; set; }
        public string usuario { get; set; }
        public string id_gasto { get; set; }
        public string id_oficina { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
