//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trabajos_distribucion
    {
        public int Id_tbl_trabajos_distribucion { get; set; }
        public string id_cliente { get; set; }
        public string id_job { get; set; }
        public string Id_empleado { get; set; }
        public Nullable<decimal> porcentaje_distribucion { get; set; }
    
        public virtual tbl_empleados tbl_empleados { get; set; }
        public virtual tbl_trabajos tbl_trabajos { get; set; }
    }
}
