//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_solicitud_facturas_distribucion_socios
    {
        public decimal id_solicitud { get; set; }
        public string Id_empleado { get; set; }
        public decimal porcentaje_distribucion { get; set; }
    
        public virtual tbl_empleados tbl_empleados { get; set; }
        public virtual tbl_solicitud_facturas tbl_solicitud_facturas { get; set; }
    }
}
