//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_niveles_empleado
    {
        public string id_oficina { get; set; }
        public string id_empleado { get; set; }
        public string id_oficina_control { get; set; }
        public string empleado_control { get; set; }
        public Nullable<decimal> del_nivel { get; set; }
        public Nullable<decimal> al_nivel { get; set; }
        public Nullable<decimal> acceso_procesos { get; set; }
        public Nullable<decimal> acceso_reportes { get; set; }
    }
}
