//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_geografia
    {
        public int Codigo_geografia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Nivel_jerarquico { get; set; }
        public string Cadena_jerarquica { get; set; }
        public Nullable<int> Codigo_geografia_padre { get; set; }
        public string Codigo_iso_alpha { get; set; }
    }
}
