//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_horas_cargadas_al_standard
    {
        public string ID_PAIS { get; set; }
        public string periodo_tep_proceso { get; set; }
        public string id_cliente { get; set; }
        public Nullable<decimal> chrg_cd_hrs { get; set; }
        public Nullable<decimal> gross_rev_local { get; set; }
        public Nullable<decimal> gross_rev { get; set; }
        public int billing_variances { get; set; }
        public string linea { get; set; }
        public string producto { get; set; }
        public string servicio { get; set; }
    }
}
