//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_revenues
    {
        public string pais { get; set; }
        public string ORDEN { get; set; }
        public string periodo { get; set; }
        public string LINEA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    }
}
