//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_oficina
    {
        public string id_oficina { get; set; }
        public string Nombre { get; set; }
        public string direccion { get; set; }
        public string periodo_proceso { get; set; }
        public string id_pais { get; set; }
        public decimal parametro_reportes { get; set; }
        public int Status { get; set; }
        public Nullable<int> permite_facturar_en_periodo { get; set; }
        public Nullable<decimal> Numero_Telefono { get; set; }
        public Nullable<decimal> Numero_Fax { get; set; }
        public string correo_electronico { get; set; }
        public string codigo_fiscal { get; set; }
    }
}
