//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_entes_clientes
    {
        public string id_pais { get; set; }
        public string id_cliente { get; set; }
        public decimal linea { get; set; }
        public string nit { get; set; }
        public string nombre { get; set; }
        public string direccion1 { get; set; }
        public string direccion2 { get; set; }
        public string direccion3 { get; set; }
        public string atencion_a { get; set; }
        public string adicional1 { get; set; }
        public string adicional2 { get; set; }
        public string codigo_municipio { get; set; }
        public string codigo_postal { get; set; }
        public string Codigo_pais_iso { get; set; }
        public string codigo_provincia { get; set; }
        public Nullable<int> estado { get; set; }
        public string correo_electronico { get; set; }
        public string ente_cliente_ubicacion { get; set; }
        public Nullable<bool> Cliente_Exonerado { get; set; }
        public string Tipo_Exoneracion { get; set; }
        public string numero_exoneracion { get; set; }
        public string Nombre_institucion_Exoneracion { get; set; }
        public Nullable<System.DateTime> Fecha_EExoneracion { get; set; }
        public Nullable<decimal> Monto_Exoneracion { get; set; }
        public Nullable<decimal> Porcentaje_CExoneracion { get; set; }
        public Nullable<decimal> id_industria { get; set; }
        public Nullable<bool> Local_Extranjero { get; set; }
        public Nullable<int> Id_Tbl_condicion_cobro { get; set; }
        public string RUC { get; set; }
    }
}
