//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Trabajos_Oficina
    {
        public string Id_Cliente { get; set; }
        public string Id_Job { get; set; }
        public string Id_oficina { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual tbl_trabajos tbl_trabajos { get; set; }
    }
}
