//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_distribuidos
    {
        public decimal id_transaccion { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string id_gasto { get; set; }
        public string id_pais { get; set; }
        public string id_cliente { get; set; }
        public string id_servicio { get; set; }
        public string id_job { get; set; }
        public string id_oficina { get; set; }
        public decimal id_linea { get; set; }
        public Nullable<decimal> id_tbl_entes_clientes { get; set; }
    }
}
