//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_documentos_fiscales
    {
        public string id_oficina { get; set; }
        public string tipo_documento { get; set; }
        public string serie { get; set; }
        public decimal numero_documento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> bienes { get; set; }
        public Nullable<decimal> servicios { get; set; }
        public Nullable<decimal> exportacion { get; set; }
        public Nullable<decimal> exento { get; set; }
        public Nullable<decimal> valor_impuesto { get; set; }
        public string concepto { get; set; }
        public string id_cliente { get; set; }
        public bool estado_anulado { get; set; }
        public string id_entidad { get; set; }
        public string tipo_documento_aplicado { get; set; }
        public Nullable<decimal> numero_documento_aplicado { get; set; }
        public string Id_pais_cliente { get; set; }
        public string Nombre_ente_cliente { get; set; }
        public string Direccion_cliente { get; set; }
        public Nullable<decimal> Tasa_cambio { get; set; }
        public Nullable<decimal> Porcentaje_iva { get; set; }
    }
}
