//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cargos_otras_oficinas
    {
        public decimal id_reporte { get; set; }
        public decimal linea { get; set; }
        public string id_pais { get; set; }
        public string id_cliente { get; set; }
        public string id_servicio { get; set; }
        public Nullable<decimal> horas { get; set; }
        public Nullable<decimal> honorarios { get; set; }
        public Nullable<decimal> gastos { get; set; }
        public Nullable<decimal> cuota_facturacion { get; set; }
    }
}
