//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tipo_documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_tipo_documento()
        {
            this.tbl_autorizacion_documentos = new HashSet<tbl_autorizacion_documentos>();
        }
    
        public string id_oficina { get; set; }
        public string id_entidad { get; set; }
        public string id_tipo_documento { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_autorizacion_documentos> tbl_autorizacion_documentos { get; set; }
        public virtual tbl_entidad_legal tbl_entidad_legal { get; set; }
    }
}
