//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_clientes
    {
        public string id_pais { get; set; }
        public string id_cliente { get; set; }
        public Nullable<decimal> id_grupo { get; set; }
        public string Razon_Social { get; set; }
        public string direccion1 { get; set; }
        public string direccion2 { get; set; }
        public string direccion3 { get; set; }
        public string exento_impuesto { get; set; }
        public string telefonos { get; set; }
        public string email { get; set; }
        public Nullable<decimal> id_industria { get; set; }
        public string contacto { get; set; }
        public string auditor_anterior { get; set; }
        public decimal estado { get; set; }
        public string nacional_id { get; set; }
        public string ciudad { get; set; }
        public string provincia { get; set; }
        public string codigo_postal { get; set; }
        public string crp { get; set; }
        public string entity_duns { get; set; }
        public string hq_parent_duns { get; set; }
        public string ultimate_parent_duns { get; set; }
        public string channel { get; set; }
        public string id_pais_cliente { get; set; }
        public string Entity_CES_id { get; set; }
        public string Party_Ref_Id { get; set; }
        public string Inmediate_Parent_Duns { get; set; }
        public string Auditor_ext { get; set; }
        public string webadress { get; set; }
        public string rnc { get; set; }
        public string fax { get; set; }
        public string cliente_referido { get; set; }
        public string parent { get; set; }
        public string global_ultimate { get; set; }
        public string namecontacto { get; set; }
        public string posicion_contac { get; set; }
        public string email_contac { get; set; }
        public string movil_contac { get; set; }
        public string cierre_anio_financiero { get; set; }
        public string Periodo_ultimo_mov { get; set; }
    }
}
