//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_documentos_gface
    {
        public string Oficina { get; set; }
        public string Entidad { get; set; }
        public string Tipo { get; set; }
        public string Serie { get; set; }
        public int Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Tipo_de_Cambio { get; set; }
        public string Referencia_Interna { get; set; }
        public string Comprador_NIT { get; set; }
        public string Comprador_Nombre { get; set; }
        public string Comprador_Direccion { get; set; }
        public string Comprador_Municipio { get; set; }
        public string Comprador_Departamento { get; set; }
        public string Comprador_Pais { get; set; }
        public string Comprador_Postal { get; set; }
        public string Comprador_Telefono { get; set; }
        public Nullable<decimal> Porcentaje_Iva { get; set; }
        public Nullable<decimal> Exportacion { get; set; }
        public Nullable<decimal> Porcentaje_Descuento { get; set; }
        public string Comprador_Direccion2 { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Total_Documento { get; set; }
    }
}
