//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_servicios()
        {
            this.tbl_trabajos = new HashSet<tbl_trabajos>();
        }
    
        public string id_servicio { get; set; }
        public string Nombre_largo { get; set; }
        public string Nombre_corto { get; set; }
        public string id_departamento { get; set; }
        public string id_producto_pwcglobal { get; set; }
    
        public virtual tbl_departamento tbl_departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trabajos> tbl_trabajos { get; set; }
    }
}
