//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_entidad_legal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_entidad_legal()
        {
            this.tbl_tipo_documento = new HashSet<tbl_tipo_documento>();
            this.tbl_frases = new HashSet<tbl_frases>();
        }
    
        public string id_oficina { get; set; }
        public string id_entidad { get; set; }
        public string Razon_social { get; set; }
        public string Direccion { get; set; }
        public string NIT { get; set; }
        public string correlativo_facturas { get; set; }
        public string correlativo_cobranzas { get; set; }
        public string correlativo_notas { get; set; }
        public string correlativo_anulaciones { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> incluido { get; set; }
        public string formato_facturas { get; set; }
        public bool financiera { get; set; }
        public string ubicacion_factura { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string origen_datos_factura { get; set; }
        public Nullable<bool> control_fel { get; set; }
        public string Clave_Acceso { get; set; }
        public string Clave_Api { get; set; }
        public string Clave_Cliente { get; set; }
        public string Certificado { get; set; }
        public string Formato_FEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tipo_documento> tbl_tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_frases> tbl_frases { get; set; }
    }
}
