//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_facturas_anuladas_finales
    {
        public string linea { get; set; }
        public string producto { get; set; }
        public string servicio { get; set; }
        public string id_oficina { get; set; }
        public string id_entidad { get; set; }
        public string tipo_documento { get; set; }
        public decimal numero_documento { get; set; }
        public Nullable<System.DateTime> fecha_anulacion { get; set; }
        public string id_cliente { get; set; }
        public Nullable<decimal> definitiva { get; set; }
    }
}
