//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tiempo_cargable_origen
    {
        public string Id_pais { get; set; }
        public string id_oficina { get; set; }
        public string periodo_tep_proceso { get; set; }
        public string id_empleado { get; set; }
        public string id_cliente { get; set; }
        public string id_job { get; set; }
        public string Id_departamento { get; set; }
        public Nullable<decimal> horas { get; set; }
        public Nullable<decimal> honorarios { get; set; }
        public Nullable<decimal> gastos { get; set; }
    }
}
