//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trabajos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_trabajos()
        {
            this.Tbl_Trabajos_Oficina = new HashSet<Tbl_Trabajos_Oficina>();
            this.tbl_trabajos_distribucion = new HashSet<tbl_trabajos_distribucion>();
        }
    
        public string id_cliente { get; set; }
        public string id_job { get; set; }
        public string id_pais { get; set; }
        public string id_oficina { get; set; }
        public string id_servicio { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> gastos_contratados { get; set; }
        public Nullable<decimal> honorarios_contratados { get; set; }
        public string id_socio { get; set; }
        public string id_encargado { get; set; }
        public string contacto { get; set; }
        public Nullable<decimal> horas_contratadas { get; set; }
        public string segundo_socio { get; set; }
        public decimal estado { get; set; }
        public Nullable<System.DateTime> fecha_inicio_job { get; set; }
        public string perform_manager { get; set; }
        public string perform_parther { get; set; }
        public string afs_number { get; set; }
        public string conting_fee_flag { get; set; }
        public string refered_by { get; set; }
        public Nullable<int> realizacion_esperada { get; set; }
        public Nullable<bool> Inactivo_Cargo_Horas { get; set; }
        public string codigo_cabys { get; set; }
        public string id_propuesta { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
    
        public virtual tbl_paises tbl_paises { get; set; }
        public virtual tbl_servicios tbl_servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Trabajos_Oficina> Tbl_Trabajos_Oficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trabajos_distribucion> tbl_trabajos_distribucion { get; set; }
    }
}
