//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detalle_cobros_anulaciones_historia
    {
        public string id_oficina { get; set; }
        public string id_entidad { get; set; }
        public string tipo_documento { get; set; }
        public string tipo_documento_aplicado { get; set; }
        public decimal numero_documento { get; set; }
        public decimal numero_documento_aplicado { get; set; }
        public Nullable<decimal> valor_aplicado { get; set; }
        public Nullable<decimal> aplicado_impuestos { get; set; }
        public Nullable<decimal> aplicado_anticipos { get; set; }
        public string tipo_factura { get; set; }
        public Nullable<decimal> aplicado_preliminar { get; set; }
        public Nullable<decimal> aplicado_definitivo { get; set; }
        public decimal aplicado_impuesto { get; set; }
        public string id_cliente { get; set; }
        public string id_job { get; set; }
        public string razon_social { get; set; }
        public string descripcion_job { get; set; }
        public string id_servicio { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
