//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detalle_cargable_temp
    {
        public string id_oficina { get; set; }
        public decimal linea { get; set; }
        public Nullable<decimal> horas { get; set; }
        public Nullable<decimal> honorarios { get; set; }
        public Nullable<decimal> gastos { get; set; }
        public Nullable<decimal> cuota_facturacion { get; set; }
        public string id_job { get; set; }
        public string descripcion_cargo { get; set; }
        public string id_oficina0 { get; set; }
        public string id_empleado { get; set; }
        public string id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_hora_captura { get; set; }
        public Nullable<decimal> id_tbl_entes_clientes { get; set; }
    
        public virtual tbl_reportes_tiempo_temp tbl_reportes_tiempo_temp { get; set; }
    }
}
