//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aut_empleadojob
    {
        public string id_oficina { get; set; }
        public string id_empleado { get; set; }
        public string id_cliente { get; set; }
        public string id_job { get; set; }
        public string periodo_tep_proceso { get; set; }
        public Nullable<decimal> tiempo_cargado { get; set; }
        public Nullable<decimal> tiempo_autorizado_team { get; set; }
        public string tiempo_autorizado_job { get; set; }
        public Nullable<decimal> autorizar_tiempo { get; set; }
        public string autorizado_carga_tiempo { get; set; }
        public string id_team { get; set; }
        public string id_pais { get; set; }
    }
}
