//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cancelacion_facturas_nc
    {
        public string linea { get; set; }
        public string producto { get; set; }
        public string servicio { get; set; }
        public string periodo_tep { get; set; }
        public string id_entidad { get; set; }
        public string tipo_documento { get; set; }
        public decimal numero_documento { get; set; }
        public string id_cliente { get; set; }
        public string tipo_documento_aplicado { get; set; }
        public decimal numero_documento_aplicado { get; set; }
        public Nullable<decimal> aplicado_definitivo { get; set; }
        public string cliente { get; set; }
        public string documento_aplicado { get; set; }
    }
}
