//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gts_automaticos_detalle
    {
        public decimal Id_transaccion { get; set; }
        public decimal Linea { get; set; }
        public string id_servicio { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
