//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_claves_empleado
    {
        public int tbl_claves_empleado_id { get; set; }
        public string id_empleado { get; set; }
        public string clave { get; set; }
        public Nullable<System.DateTime> fecha_clave { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
        public Nullable<bool> cambia_clave { get; set; }
    }
}
