//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_departamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_departamento()
        {
            this.tbl_servicios = new HashSet<tbl_servicios>();
        }
    
        public string id_departamento { get; set; }
        public string Nombre_largo { get; set; }
        public string Nombre_reportes { get; set; }
        public string id_grupos { get; set; }
        public string id_oficina { get; set; }
        public string Socio { get; set; }
        public string Id_linea_pwcglobal { get; set; }
        public string code_center_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_servicios> tbl_servicios { get; set; }
    }
}
