//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reserva_tep
    {
        public string PAIS { get; set; }
        public string LINEA { get; set; }
        public string PRODUCTO { get; set; }
        public string SERVICIO { get; set; }
        public string ID_CLIENTE { get; set; }
        public string ID_JOB { get; set; }
        public Nullable<decimal> RESERVATEP { get; set; }
    }
}
