//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reportes_tiempo
    {
        public decimal id_reporte { get; set; }
        public string id_oficina { get; set; }
        public string id_empleado { get; set; }
        public string periodo_tep_proceso { get; set; }
        public string periodo_tep_corresponde { get; set; }
        public Nullable<decimal> tasa_cambio { get; set; }
        public Nullable<decimal> de_dia { get; set; }
        public Nullable<decimal> a_dia { get; set; }
        public string captado_por { get; set; }
    }
}
