//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_saldostep_cierre
    {
        public string periodo_tep { get; set; }
        public string id_pais { get; set; }
        public string id_cliente { get; set; }
        public string id_oficina { get; set; }
        public string id_empleado { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public Nullable<decimal> Honorarios { get; set; }
        public Nullable<decimal> Gastos { get; set; }
        public string id_servicio { get; set; }
        public decimal id_job { get; set; }
        public string id_oficina0 { get; set; }
    }
}
