//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_no_cargables
    {
        public decimal id_reporte { get; set; }
        public decimal linea { get; set; }
        public string id_concepto { get; set; }
        public Nullable<decimal> horas { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> horasporautorizar { get; set; }
        public Nullable<decimal> horasrechazadas { get; set; }
        public Nullable<decimal> horascaptadasweb { get; set; }
        public string id_departamento { get; set; }
        public string id_team { get; set; }
    }
}
