//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Integracion_tep_Empleado_Gasto
    {
        public decimal Transaction_Register { get; set; }
        public string anio { get; set; }
        public string Periodo { get; set; }
        public string Cliente { get; set; }
        public string id_Servicio { get; set; }
        public string Tipo { get; set; }
        public string Documento { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Horas { get; set; }
        public decimal Honorarios { get; set; }
        public decimal Gastos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Explicacion { get; set; }
        public string id_job { get; set; }
        public string id_oficina { get; set; }
    }
}
