//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_frases
    {
        public int Id_tbl_frase { get; set; }
        public int Codigo_Escenario { get; set; }
        public int Tipo_Frase { get; set; }
        public string Id_oficina { get; set; }
        public string Id_entidad { get; set; }
    
        public virtual tbl_entidad_legal tbl_entidad_legal { get; set; }
    }
}
