//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_solicitud_facturas_temp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_solicitud_facturas_temp()
        {
            this.tbl_det_Solicitud_temp = new HashSet<tbl_det_Solicitud_temp>();
        }
    
        public Nullable<System.DateTime> fecha { get; set; }
        public string id_oficina { get; set; }
        public string id_empleado { get; set; }
        public string id_job { get; set; }
        public string id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_a_emitir { get; set; }
        public string id_entidad { get; set; }
        public string facturar_en_perido { get; set; }
        public string tipo_entrega { get; set; }
        public Nullable<decimal> total_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_tentativa_cobro { get; set; }
        public string instrucciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_det_Solicitud_temp> tbl_det_Solicitud_temp { get; set; }
    }
}
