//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aplicacion_tep
    {
        public decimal id_transaccion { get; set; }
        public string id_oficina { get; set; }
        public string id_empleado { get; set; }
        public Nullable<decimal> horas { get; set; }
        public Nullable<decimal> honorarios { get; set; }
        public Nullable<decimal> gastos { get; set; }
        public Nullable<decimal> horas_reporte { get; set; }
        public Nullable<decimal> honorarios_reporte { get; set; }
        public Nullable<decimal> gastos_reporte { get; set; }
        public string id_oficina0 { get; set; }
    }
}
