//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_contabilizacion_servicios
    {
        public string ID_PAIS { get; set; }
        public string ID_OFICINA { get; set; }
        public string ID_SERVICIO { get; set; }
        public string ID_CUENTA { get; set; }
        public string ID_AUXILIAR { get; set; }
        public string ID_DEPARTAMENTO { get; set; }
    }
}
