//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_concepto_no_cargable
    {
        public string id_concepto { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> solicita_descripcion { get; set; }
        public decimal inactivar { get; set; }
        public Nullable<bool> Distribucion_Proporcional_socios { get; set; }
    }
}
