//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tasas_de_cambio
    {
        public string id_pais { get; set; }
        public string periodo_tep { get; set; }
        public decimal tasa_de_cambio { get; set; }
    }
}
