//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empleado_entidad_legal
    {
        public int Id_Tbl_Empleado_Entidad_Legal { get; set; }
        public string Id_Oficina { get; set; }
        public string Id_Entidad { get; set; }
        public string Id_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Expira_Token { get; set; }
        public string FE_Token { get; set; }
    }
}
