//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_distribucion_gastos
    {
        public decimal id_transaccion { get; set; }
        public string Documento_referencia { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public string forma_distribucion { get; set; }
        public string periodo_tep_proceso { get; set; }
        public string id_oficina { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string id_entidad { get; set; }
    }
}
