//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Actividad_Economica_CR
    {
        public string Id_Actividad_Economica_CR { get; set; }
        public string Descripcion_Actividad_Economica_CR { get; set; }
    }
}
