//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_entes_solicitud
    {
        public decimal id_solicitud { get; set; }
        public decimal linea { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<System.DateTime> Fecha_autorizacion { get; set; }
        public Nullable<decimal> Estado { get; set; }
    }
}
