//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_industrias
    {
        public decimal id_industria { get; set; }
        public string nombre { get; set; }
        public string id_sector { get; set; }
        public string id_industria_pwcglobal { get; set; }
    }
}
