//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_provincia_depto
    {
        public string Codigo_iso_alpha { get; set; }
        public string Codigo_provincia { get; set; }
        public string Descripcion { get; set; }
    }
}
