//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lineas
    {
        public string id_grupos { get; set; }
        public string descripcion { get; set; }
        public string id_oficina { get; set; }
        public string Socio_encargado { get; set; }
        public string id_linea_pwcglobal { get; set; }
    }
}
