//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_paises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_paises()
        {
            this.tbl_trabajos = new HashSet<tbl_trabajos>();
        }
    
        public string id_pais { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Tasa_Cambio { get; set; }
        public string Moneda { get; set; }
        public string Periodo_Proceso { get; set; }
        public string Situacion { get; set; }
        public Nullable<decimal> inicia_periodo { get; set; }
        public Nullable<decimal> finaliza_periodo { get; set; }
        public string id_territory { get; set; }
        public string iso_char2 { get; set; }
        public string codigo_pais { get; set; }
        public string paisSynId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trabajos> tbl_trabajos { get; set; }
    }
}
