//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Detalle_Sol_temp
    {
        public decimal line_detalle { get; set; }
        public decimal id_solicitud { get; set; }
        public decimal linea { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Impuesto_por { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Atencion_a { get; set; }
        public Nullable<bool> es_linea_fiscal { get; set; }
        public Nullable<decimal> Descuento_linea { get; set; }
        public string Descripcion_comercial { get; set; }
        public Nullable<decimal> Valor_local { get; set; }
    
        public virtual tbl_solicitud_temp tbl_solicitud_temp { get; set; }
    }
}
