//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cuenta_corriente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cuenta_corriente()
        {
            this.tbl_cuenta_corriente_gestion_cobro = new HashSet<tbl_cuenta_corriente_gestion_cobro>();
        }
    
        public string id_oficina { get; set; }
        public string id_entidad { get; set; }
        public string tipo_documento { get; set; }
        public decimal numero_documento { get; set; }
        public string periodo_tep { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<decimal> impuesto_porcentaje { get; set; }
        public string impuesto_incluido { get; set; }
        public Nullable<decimal> valor_impuesto { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> saldo_impuesto { get; set; }
        public Nullable<decimal> factura_preliminar { get; set; }
        public Nullable<decimal> anticipo_aplicar { get; set; }
        public Nullable<decimal> factura_definitiva { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> id_solicitud { get; set; }
        public string id_job { get; set; }
        public string id_cliente { get; set; }
        public Nullable<decimal> tasa_cambio { get; set; }
        public Nullable<decimal> flag_impreso { get; set; }
        public decimal estado { get; set; }
        public Nullable<decimal> linea { get; set; }
        public string numero_documento_fiscal_electronico { get; set; }
        public string clave_electronica { get; set; }
        public string Numero_documento_sustituye { get; set; }
        public Nullable<bool> Lenguaje_Impresion_spanish1 { get; set; }
        public Nullable<decimal> valor_total_moneda_local { get; set; }
        public Nullable<System.DateTime> fecha_timbrado { get; set; }
        public string numero_documento_fiscal_electronico_cobro { get; set; }
        public string clave_electronica_cobro { get; set; }
        public string tipo_documento_fiscal { get; set; }
    
        public virtual tbl_certificacion_documento tbl_certificacion_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cuenta_corriente_gestion_cobro> tbl_cuenta_corriente_gestion_cobro { get; set; }
    }
}
