//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_detalle_captura_temp_Nocargable
    {
        public string descripcion { get; set; }
        public Nullable<decimal> horas { get; set; }
        public string id_empleado { get; set; }
        public string nombre_empleado { get; set; }
        public string id_oficina { get; set; }
        public string Nombre { get; set; }
        public string id_concepto { get; set; }
        public string descConcepto { get; set; }
        public decimal linea { get; set; }
    }
}
