//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiempoEnProcesoDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Empleados_Datos
    {
        public string id_oficina { get; set; }
        public string id_empleado { get; set; }
        public string iniciales { get; set; }
        public string id_puesto { get; set; }
        public string id_departamento { get; set; }
        public string Nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<decimal> cuota_facturacion_local { get; set; }
        public Nullable<decimal> cuota_facturacion_interamerica { get; set; }
        public string situacion_actual { get; set; }
        public string ultimo_reporte_entregado { get; set; }
        public string clave { get; set; }
        public Nullable<decimal> presupuesto_horas { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public decimal usuario_administrativo { get; set; }
        public string id_team { get; set; }
        public string cem_costo { get; set; }
        public Nullable<System.DateTime> ultima_fecha_pass { get; set; }
        public bool logged { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public int tbl_claves_empleado_id { get; set; }
        public Nullable<bool> cambia_clave { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
    }
}
